hosts = {
    "prometheus"   => {"memory" => "512", "cpu" => "1", "ip" => "150", "image" => "debian/bookworm64"},
}

Vagrant.configure ("2") do |config|
    config.vm.synced_folder "config/", "/etc/prometheus"
    
    config.vm.provision "shell", path: "scripts/startup-prometheus.sh"
    config.vm.provision "shell", path: "scripts/startup-node_exporter.sh"
    config.vm.provision "shell", path: "scripts/grafana.sh"

    hosts.each do |name, conf|
        config.vm.define "#{name}" do |server|
            server.vm.box = "#{conf["image"]}"
            server.vm.hostname = "#{name}"
            server.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
            server.vm.provider "virtualbox" do |metric|
                metric.name = "#{name}"
                metric.memory = conf["memory"]
                metric.cpus = conf["cpu"]
                metric.customize ["modifyvm", :id, "--groups", "/study"]
            end
        end
    end
end
