groups:
  - name: my firts alerts
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      annotations:
        title: 'Finish test instance  {{ $labels.instance }}'
        description: 'My first alert in prometheus'
      labels:
        severity: 'critical'
    - alert: NodeLoad
      expr: node_load1 > 1.0
      for: 1m
      annotations:
        title: 'Node Load  {{ $labels.instance }}'
        description: 'My first alert in prometheus'
    - alert: DiskUsage
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 90
      labels:
        instance: '{{ $labels.instance }}:{{ $labels.mountpoint }}'
      annotations:
        title: 'Disk usage'
        description: 'Disk usage'
